name: Create Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create addon package
        run: |
          mkdir -p package/DiabolicUI3
          rsync -av --exclude='.git*' --exclude='package' --exclude='RELEASE_NOTES*' ./ package/DiabolicUI3/
          cd package
          zip -r DiabolicUI3.zip DiabolicUI3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: package/DiabolicUI3.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
